Update installers

diff --git a/install-prod b/install-prod
--- a/install-prod
+++ b/install-prod
@@ -4,20 +4,24 @@ PROJECT_DIR="/app"
 RELAY_DIR="/deploy-relay"
 DOCKER_DIR="$PROJECT_DIR/docker"
 
-# Remote is always prod
+# Remote is always prod mode, to prevent debug in public
 APP_ENV=prod
 
+INSTALL_TIME="$(date '+%m-%d-%Y %T')"
 INSTALL_ENV_VARS="/root/.env-install"
 INSTALL_ERROR_LOG="/var/log/install-script-errors.log"
 
 SETUP_ERRORS=()
 
 if [ -f "$INSTALL_ENV_VARS" ]; then
-  source "$INSTALL_ENV_VARS"
-
-  # Delete .env-install file
-  rm "$INSTALL_ENV_VARS"
+  SETUP_ERRORS+="Missing $INSTALL_ENV_VARS file."
 fi
+
+# Environment variables checked below are in the .env-install file.
+source "$INSTALL_ENV_VARS"
+
+# Delete .env-install file
+rm "$INSTALL_ENV_VARS"
 
 if [ -z "$DEPLOY_ENV" ]; then
   SETUP_ERRORS+="DEPLOY_ENV variable is required."
@@ -40,22 +44,22 @@ if [ -z "$SITE_USER_RSA_PUB_KEY_VALUE" ]; then
 fi
 
 if [ "${#SETUP_ERRORS[*]}" -gt 0 ]; then
-  touch "$INSTALL_ERROR_LOG"
-
-  echo "$(date '+%m-%d-%Y %T')" >> $INSTALL_ERROR_LOG
+  touch "$INSTALL_SCRIPT_ERROR_LOG"
 
   for SETUP_ERROR in "${SETUP_ERRORS[@]}"
   do
-    echo "$SETUP_ERROR" >> "$INSTALL_ERROR_LOG"
+    echo "[$INSTALL_TIME] $SETUP_ERROR" >> "$INSTALL_SCRIPT_ERROR_LOG"
+
+    printf "\n%s\n" "Error(s) on installation. See $INSTALL_SCRIPT_ERROR_LOG for details."
   done
 
-  exit
+  exit 1
 fi
 
+DEPLOY_BRANCH="main-stable"
+
 if [ "$DEPLOY_ENV" == "dev" ]; then
-  DEPLOY_BRANCH=main-edge
-elif [ "$DEPLOY_ENV" == "prod" ]; then
-  DEPLOY_BRANCH=main-stable
+  DEPLOY_BRANCH="main-edge"
 fi
 
 export PROJECT_DIR
@@ -70,7 +74,7 @@ export SITE_USER_RSA_PUB_KEY_VALUE
 # This sets the variable $IPADDR to the IP address the new Linode receives.
 IPADDR=$(ip -4 addr show eth0 | awk '/inet / { print $2 }' | sed 's/addr://')
 
-# This section sets the Fully Qualified Domain Name (FQDN) in the hosts file.
+# This section sets the Fully Qualified DOMAIN Name (FQDN) in the hosts file.
 echo $IPADDR $FQDN $HOSTNAME >> /etc/hosts
 
 # This updates the packages on the system from the distribution repositories.
@@ -81,13 +85,13 @@ apt-get -y upgrade
 echo $HOSTNAME > /etc/hostname
 hostname -F /etc/hostname
 
+# Docker
+apt-get -y install docker.io
+
 # For latest Docker Compose
 add-apt-repository universe
 apt-get -y install python3-pip
 pip3 install docker-compose
-
-# Docker
-apt-get -y install docker.io
 
 systemctl start docker
 systemctl enable docker
@@ -96,7 +100,13 @@ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o 
 
 apt-get -y install git mlocate
 
-bash <(wget -qO - https://raw.githubusercontent.com/jfdialogs/linode-scripts/main/install-site-user)
+INSTALL_SITE_USER="/root/install-site-user"
+
+wget -qO - https://raw.githubusercontent.com/jfdialogs/linode-scripts/main/install-site-user "$INSTALL_SITE_USER"
+
+chmod u+x "$INSTALL_SITE_USER"
+
+"$INSTALL_SITE_USER"
 
 HAS_SITE_USER="$(getent passwd $SITE_USER)"
 
@@ -115,6 +125,7 @@ cd "$PROJECT_DIR"
 
 chown -R "$SITE_USER" "$PROJECT_DIR"
 chown -R "$SITE_USER" "$RELAY_DIR"
+
 chgrp -R "$SITE_USER" "$PROJECT_DIR"
 chgrp -R "$SITE_USER" "$RELAY_DIR"
 
@@ -122,8 +133,10 @@ git config --global http.postBuffer 524288000
 
 su -c "git clone -b $DEPLOY_BRANCH $GIT_REPO $PROJECT_DIR" - "$SITE_USER"
 
-"$DOCKER_DIR/server" install-remote-prod
-"$DOCKER_DIR/server" install-hooks
+DOMAIN="$DOCKER_DIR/server"
+
+"$DOMAIN" install-remote-prod
+"$DOMAIN" install-hooks
 
 cd "$PROJECT_DIR"
 
diff --git a/install-site-user b/install-site-user
--- a/install-site-user
+++ b/install-site-user
@@ -1,70 +1,96 @@
 #!/usr/bin/env bash
 
+INSTALL_SCRIPT_ERROR_LOG="/var/log/install-script-errors.log"
+
+SETUP_ERRORS=()
+
+if [ -z "$SITE_USER" ]; then
+  SETUP_ERRORS+="SITE_USER variable is required."
+fi
+
+if [ -z "$SITE_USER_RSA_PRIV_KEY_VALUE" ]; then
+  SETUP_ERRORS+="SITE_USER_RSA_PRIV_KEY_VALUE variable is required."
+fi
+
+if [ -z "SITE_USER_RSA_PUB_KEY_VALUE" ]; then
+  SETUP_ERRORS+="SITE_USER_RSA_PUB_KEY_VALUE variable is required."
+fi
+
+if [ "${#SETUP_ERRORS[*]}" -gt 0 ]; then
+  touch "$INSTALL_SCRIPT_ERROR_LOG"
+
+  LOG_TIME="$(date '+%m-%d-%Y %T')"
+
+  for SETUP_ERROR in "${SETUP_ERRORS[@]}"
+  do
+    echo "[$LOG_TIME] $SETUP_ERROR" >> "$INSTALL_SCRIPT_ERROR_LOG"
+
+    printf "\n%s\n" "Error(s) on installation. See $INSTALL_SCRIPT_ERROR_LOG for details."
+  done
+
+  exit 1
+fi
+
 # See https://unix.stackexchange.com/a/210232
 
-function make_site_user {
-  SITE_USER="$1"
-  SITE_USER_RSA_PRIV_KEY_VALUE="$2"
-  SITE_USER_RSA_PUB_KEY_VALUE="$3"
+SITE_USER_RSA_PRIV_KEY_VALUE="$2"
+SITE_USER_RSA_PUB_KEY_VALUE="$3"
 
-  SITE_USER_HOME="/home/$SITE_USER"
-  SITE_USER_SSH_DIR="$SITE_USER_HOME/.ssh"
-  SITE_USER_RSA_PRIV_KEY="$SITE_USER_SSH_DIR/id_rsa"
-  SITE_USER_RSA_PUB_KEY="$SITE_USER_RSA_PRIV_KEY.pub"
+SITE_USER_HOME="/home/$SITE_USER"
+SITE_USER_SSH_DIR="$SITE_USER_HOME/.ssh"
+SITE_USER_RSA_PRIV_KEY="$SITE_USER_SSH_DIR/id_rsa"
+SITE_USER_RSA_PUB_KEY="$SITE_USER_RSA_PRIV_KEY.pub"
 
-  KNOWN_HOSTS="$SITE_USER_SSH_DIR/known_hosts"
-  AUTHORIZED_KEYS="$SITE_USER_SSH_DIR/authorized_keys"
+KNOWN_HOSTS="$SITE_USER_SSH_DIR/known_hosts"
+AUTHORIZED_KEYS="$SITE_USER_SSH_DIR/authorized_keys"
 
-  useradd -m -d "$SITE_USER_HOME" -s /bin/bash "$SITE_USER"
+useradd -m -d "$SITE_USER_HOME" -s /bin/bash "$SITE_USER"
 
-  mkdir "$SITE_USER_SSH_DIR"
-  touch "$AUTHORIZED_KEYS"
-  touch "$KNOWN_HOSTS"
+mkdir "$SITE_USER_SSH_DIR"
+touch "$AUTHORIZED_KEYS"
+touch "$KNOWN_HOSTS"
 
-  GITHUB_KEY_HOST="github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
-  GITHUB_KEY_IPS[0]="140.82.114.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
-  GITHUB_KEY_IPS[1]="140.82.112.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
-  GITHUB_KEY_IPS[2]="140.82.112.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
-  GITHUB_KEY_IPS[3]="140.82.113.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
-  GITHUB_KEY_IPS[4]="140.82.113.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
-  GITHUB_KEY_IPS[5]="140.82.114.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
+GITHUB_KEY_HOST="github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
+GITHUB_KEY_IPS[0]="140.82.114.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
+GITHUB_KEY_IPS[1]="140.82.112.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
+GITHUB_KEY_IPS[2]="140.82.112.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
+GITHUB_KEY_IPS[3]="140.82.113.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
+GITHUB_KEY_IPS[4]="140.82.113.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
+GITHUB_KEY_IPS[5]="140.82.114.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
 
-  echo "$GITHUB_KEY_HOST" >> "$KNOWN_HOSTS"
+echo "$GITHUB_KEY_HOST" >> "$KNOWN_HOSTS"
 
-  for GITHUB_KEY_IP in "${GITHUB_KEY_IPS[@]}"
-  do
-      echo "$GITHUB_KEY_IP" >> "$KNOWN_HOSTS"
-  done
+for GITHUB_KEY_IP in "${GITHUB_KEY_IPS[@]}"
+do
+    echo "$GITHUB_KEY_IP" >> "$KNOWN_HOSTS"
+done
 
-  ASSEMBLA_KEY_HOSTS[0]="git.assembla.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAr06hg4ep5IKc85rjYZkEmer+BMkpLfsYi7iOMWytiqyow0jqMiVg7t32a4WW0349QV4rmfcMg5ULuIP//mBjSb2G1jSmqPvWx4JCzZLKu3nmsx1YdBWmVvn/qyVLQ5E+NCSkJJORKqIIgiL1WuAEaxUODYmBExwv1eMZWBpyeKZrrsBEmogKt2Q+igQ31+rb1fQI9/hDE+SktOpT9sWJ9brSDgsQNXAtV52DFDA8mzq7FL+4TbLjDoDdK7v3LFYn2cnN2kD57gW8qvP6V6mrkjc6I2aCNBHwdcIynUQ8HKdU+Sd4u7pZsCCK7odgPCcM5Jj+/PladSR8+DCtvs6JWw=="
-  ASSEMBLA_KEY_HOSTS[1]="git.assembla.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCgF2nbN5k2W4gUAkyE7+iI5T5Ng2f5xiL4+gGkARwRhftogPzqYi3+IM4PZnDW6nKPzWGo+b+mx2LR4FO0+2IE="
+ASSEMBLA_KEY_HOSTS[0]="git.assembla.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAr06hg4ep5IKc85rjYZkEmer+BMkpLfsYi7iOMWytiqyow0jqMiVg7t32a4WW0349QV4rmfcMg5ULuIP//mBjSb2G1jSmqPvWx4JCzZLKu3nmsx1YdBWmVvn/qyVLQ5E+NCSkJJORKqIIgiL1WuAEaxUODYmBExwv1eMZWBpyeKZrrsBEmogKt2Q+igQ31+rb1fQI9/hDE+SktOpT9sWJ9brSDgsQNXAtV52DFDA8mzq7FL+4TbLjDoDdK7v3LFYn2cnN2kD57gW8qvP6V6mrkjc6I2aCNBHwdcIynUQ8HKdU+Sd4u7pZsCCK7odgPCcM5Jj+/PladSR8+DCtvs6JWw=="
+ASSEMBLA_KEY_HOSTS[1]="git.assembla.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCgF2nbN5k2W4gUAkyE7+iI5T5Ng2f5xiL4+gGkARwRhftogPzqYi3+IM4PZnDW6nKPzWGo+b+mx2LR4FO0+2IE="
 
-  for ASSEMBLA_KEY_HOST in "${ASSEMBLA_KEY_HOSTS[@]}"
-  do
-      echo "$ASSEMBLA_KEY_HOST" >> "$KNOWN_HOSTS"
-  done
+for ASSEMBLA_KEY_HOST in "${ASSEMBLA_KEY_HOSTS[@]}"
+do
+    echo "$ASSEMBLA_KEY_HOST" >> "$KNOWN_HOSTS"
+done
 
-  echo "$SITE_USER_RSA_PRIV_KEY_VALUE" > "$SITE_USER_RSA_PRIV_KEY"
-  echo "$SITE_USER_RSA_PUB_KEY_VALUE" > "$SITE_USER_RSA_PUB_KEY"
+echo "$SITE_USER_RSA_PRIV_KEY_VALUE" > "$SITE_USER_RSA_PRIV_KEY"
+echo "$SITE_USER_RSA_PUB_KEY_VALUE" > "$SITE_USER_RSA_PUB_KEY"
 
-  chmod 0600 "$SITE_USER_RSA_PRIV_KEY"
+chmod 0600 "$SITE_USER_RSA_PRIV_KEY"
 
-  eval $(ssh-agent -s)
-  ssh-add "$SITE_USER_RSA_PRIV_KEY"
+eval $(ssh-agent -s)
+ssh-add "$SITE_USER_RSA_PRIV_KEY"
 
-  chown -R "$SITE_USER:$SITE_USER" "$SITE_USER_SSH_DIR"
-  chmod 700 "$SITE_USER_SSH_DIR"
-  chmod 600 "$SITE_USER_SSH_DIR/known_hosts"
-  chmod 600 "$SITE_USER_SSH_DIR/authorized_keys"
-  chmod go-w "$SITE_USER_HOME"
+chown -R "$SITE_USER:$SITE_USER" "$SITE_USER_SSH_DIR"
+chmod 700 "$SITE_USER_SSH_DIR"
+chmod 600 "$SITE_USER_SSH_DIR/known_hosts"
+chmod 600 "$SITE_USER_SSH_DIR/authorized_keys"
+chmod go-w "$SITE_USER_HOME"
 
-  usermod -aG www-data "$SITE_USER"
-  usermod -aG docker "$SITE_USER"
-  usermod -aG sudo "$SITE_USER"
+usermod -aG www-data "$SITE_USER"
+usermod -aG docker "$SITE_USER"
+usermod -aG sudo "$SITE_USER"
 
-  echo "$SITE_USER ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/$SITE_USER"
+echo "$SITE_USER ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/$SITE_USER"
 
-  service sshd restart
-}
-
-make_site_user "$SITE_USER" "$SITE_USER_RSA_PRIV_KEY_VALUE" "$SITE_USER_RSA_PUB_KEY_VALUE"
+service sshd restart
